name: Unity Activation (one-time)
on: workflow_dispatch

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.27f1
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.27f1.alf
          path: ./*.alf
